cargo-features = ["different-binary-name"]

[package]
name = "svboot"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "svboot"
filename = "svboot.elf"

[dependencies]
fdt = "0.1.5"
svbootlib = { path = "../svbootlib" }
svpci = { path = "../svpci" }
