cargo-features = ["different-binary-name"]

[package]
name = "svkernel"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "svkernel"
filename = "svkernel.elf"

[dependencies]
ctor_bare = "0.2.1"
fdt = "0.1.5"
spin = "0.10.0"
talc = "4.4.3"
