cargo-features = ["different-binary-name"]

[package]
name = "svkernel"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "svkernel"
filename = "svkernel.elf"

[dependencies]
sve = { path = "../../common/sve" }
