[package]
name = "svetool"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { version = "2.0.1", features = ["serde"] }
clap = "4.5.39"
elf_parser = "0.1.1"
serde = { version = "1.0.219", features = ["derive"] }
sve = { path = "../../common/sve", features = ["std"] }
