[package]
name = "svetool"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
object = "0.37.1"
sve = { path = "../../system/sve" }
svelib = { path = "../svelib" }